### PR TITLE
Problem 2 solved

### PR DESCRIPTION
**Pull request by likith1908**

### CODE REVIEW

**Review by raynimit54 — CHANGES_REQUESTED** [review]
you are pushing same file twice and also code isnt working

**Comment by likith1908** [comment]
what should i do know?

**Comment by likith1908** [comment]
[image: Screenshot 2021-10-30 at 12.20.12 PM.png]


*THE CODE IS WORKING!!*

**Comment by AnantaSrikar** [comment]
Issues resolved. Merging.

**Pull request merged**
