### PR TITLE
problem 9 solved

### PR DESCRIPTION
**Pull request by fayaque-ali**

### CODE REVIEW

**Comment by Enigma-Admin** [comment]
Your code will be reviewed soon. Make a new PR after your code is merged. Till then, Happy Coding !!

**Review by Rounak-Das-02 — CHANGES_REQUESTED** [review]
This program doesn't do what it is supposed to. :(
Please re-check the question again and solve it.
Good Effort, Happy Coding ...

**Comment by fayaque-ali** [comment]
should I commit again?

**Comment by fayaque-ali** [comment]
I have made the changes, the code works now. Should I commit again?

**Comment by Rounak-Das-02** [comment]
Yep, commit again

**Review by Rounak-Das-02 — APPROVED** [review]
Cool! Works fine .. 
Merging now ...

**Pull request closed without merging**
