### PR TITLE
solved problem 3 in level 1

### PR DESCRIPTION
**Pull request by Nikshep15**
solved problem 3 in level 1

### CODE REVIEW

**Comment by Enigma-Admin** [comment]
Your code will be reviewed soon. Make a new PR after your code is merged. Till then, Happy Coding !!

**Review by AnantaSrikar — CHANGES_REQUESTED** [review]
The code has some runtime errors. Try comparing the output for testcase 1 with your code.

**Comment by Nikshep15** [comment]
Modified the code satisfying all the cases.

**Review by AnantaSrikar — APPROVED** [review]
Perfect! Merging.

**Pull request merged**
